name        : libmpeg2
version     : 0.5.1
release     : 2
source      :
    - http://libmpeg2.sourceforge.net/files/libmpeg2-0.5.1.tar.gz : dee22e893cb5fc2b2b6ebd60b88478ab8556cb3b93f9a0d7ce8f3b61851871d4
homepage    : http://libmpeg2.sourceforge.net/
license     : GPL-2.0
component   :
    - multimedia.codecs
    - utils: multimedia.codecs
summary     :
    - A free MPEG-2 video stream decoder
    - devel: Development files for libmpeg2
    - utils: Command line utilities for libmpeg2
description :
    - A free MPEG-2 video stream decoder
    - devel: Development files for libmpeg2
    - utils: Command line utilities for libmpeg2
patterns    :
    - utils:
        - /usr/bin
        - /usr/share/doc
        - /usr/share/man
builddeps   :
    - pkgconfig(ice)
    - pkgconfig(xext)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
